# Generated by Django 3.1.5 on 2021-01-26 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tshop', '0003_sizevariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='tshirt',
            name='slug',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
